auth:
  postgresPassword: "sinkpass"
  username: "sinkuser"
  password: "sinkpass"
  database: "sinkdb"

primary:
  persistence:
    enabled: false   # no PVC needed on local

resources:
  requests:
    cpu: 100m
    memory: 256Mi
