auth:
  postgresPassword: "localdev"
  username: "myuser"
  password: "localdev"
  database: "mydb"

primary:
  persistence:
    enabled: false   # no PVC needed on local

resources:
  requests:
    cpu: 100m
    memory: 256Mi
