apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: metabase
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  project: default
  sources:
    - repoURL: ghcr.io/imdineshsandaru
      chart: metabase
      targetRevision: "2.27.1"
      helm:
        valueFiles:
          - $values/envs/local/metabase/values.yaml
    - repoURL: https://github.com/imdineshsandaru/k8s-deployments
      targetRevision: HEAD
      ref: values
  destination:
    server: https://kubernetes.default.svc
    namespace: metabase
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
