apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sf-cdc-producer
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "3"
spec:
  project: default
  source:
    repoURL: https://github.com/imdineshsandaru/k8s-deployments
    targetRevision: HEAD
    path: manifests/local/sf-cdc-producer
  destination:
    server: https://kubernetes.default.svc
    namespace: kafka
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
