apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: strimzi-operator
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  project: default
  sources:
    # Reference quay.io directly — no need to re-publish the operator chart
    - repoURL: quay.io/strimzi-helm
      chart: strimzi-kafka-operator
      targetRevision: "0.51.0"
      helm:
        valueFiles:
          - $values/envs/local/strimzi-operator/values.yaml
    - repoURL: https://github.com/imdineshsandaru/k8s-deployments
      targetRevision: HEAD
      ref: values
  destination:
    server: https://kubernetes.default.svc
    namespace: kafka
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
